# Generated by Django 4.2.27 on 2026-01-16 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchasing", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "SUPPLIER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchasing.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_items",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="store",
            field=models.ForeignKey(
                help_text="Receiving location",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="purchasing.supplier",
            ),
        ),
        migrations.AddField(
            model_name="grnitem",
            name="grn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchasing.goodsreceiptnote",
            ),
        ),
        migrations.AddField(
            model_name="grnitem",
            name="po_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_items",
                to="purchasing.purchaseorderitem",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="purchasing.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_grns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
