# Generated by Django 4.2.27 on 2026-01-16 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                help_text="Sales staff who created the order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                help_text="Fulfillment location",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="sales.order",
            ),
        ),
    ]
