# Generated by Django 4.2.27 on 2026-01-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        default=10, help_text="Alert when stock falls below this level"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["variant", "location"],
            },
        ),
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, help_text="Total quantity in stock"),
                ),
                (
                    "reserved_quantity",
                    models.IntegerField(
                        default=0, help_text="Quantity reserved for pending orders"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["variant", "location"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                            ("RETURN", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Positive for IN, negative for OUT"),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("PO", "Purchase Order"),
                            ("SO", "Sales Order"),
                            ("TRANSFER", "Stock Transfer"),
                            ("RETURN", "Return"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(help_text="ID of the related record"),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
