# Generated by Django 4.2.27 on 2026-01-16 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_alerts",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_alerts",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockrecord",
            unique_together={("variant", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="stockalert",
            unique_together={("variant", "location")},
        ),
    ]
